env:
  MAVEN_OPTS: -Xmx768m
  MAVEN_ARGS: -DskipTests -Drat.skip=true

buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: Blazar-Buildpack-Java
  branch: v2

stepActivation:
  notify:
    branches: [trunk]
